language: php

# list any PHP version you want to test against
php:
  # specify the extend version
  - 5.3.8
  # or just the major version
  - 5.4

# optional before script, for example to install xdebug
before_script: pyrus install pecl/xdebug

# omitting "script:" will default to phpunit
script: phpunit --coverage-text
